### ISSUE TITLE
MQTT retry (how to handle if broker is offline)

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/bacnet-server-c#25]
also is there any retry on sending the MQTT message to the broker

eg, a value changes on the BACnet-server and you try to send the broker a message will you retry on fail (eg mqtt-broker is offline)

**Comment by shomaglasang** [comment]
@NubeDev mate, i'll add the retry up to 5 times (default). retry_interval 10secs (default). these values can be configured in the yaml file

**Comment by shomaglasang** [comment]
@NubeDev This is included in v0.0.23. Please add the following 3 key/value pairs under mqtt section in yaml config.
```
mqtt:
  --
  retry_enable: true
  retry_limit: 5
  retry_interval: 10
```
